### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [octarect/refined.zsh#1]

**Comment by octarect** [comment]
@unixorn 
Sorry for the late reply.

I added a screen shot of this prompt. This is a direct link to the image file;  
https://github.com/octarect/clarity.zsh/blob/638efb7bd9cc0fe6429e91e29b1b6dee2b35c2ad/img/screenshot.gif?raw=true

Thank you for your advice. :>

**Comment by unixorn** [comment]
Added to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list.
